sudo: false

language: php

os:
  - linux

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

env:
  matrix:
    - DRIVER="phpdbg" DEPENDENCIES="high"
    - OS=debian DIST=stretch

  global:
    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest"

matrix:
  include:
    - php: 7
    - php: 7.1
    - php: 7.2
    - php: 7.3

install:
  - travis_retry composer install --no-interaction

before_script: composer run db

script:
  - phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.clover
